server:
  port: 9002
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chencytech/spring-cloud-examples.git # 配置git仓库的地址
          search-paths: config  # git仓库地址下的相对地址(如何直接使用仓库根目录的话，就不用配置此路径)，可以配置多个，用,分割。
          # username:   # git仓库的账号
          # password:   # git仓库的密码

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka （单机）
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/ #（集群）
  instance:
    instance-id: spring-cloud-config-server9001 # 自定义服务名称信息
    prefer-ip-address: true # 访问路径可以现实IP